@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.crystal.spell_card;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;