@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.crystal.touhou_little_maid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;